### ISSUE TITLE
Plugin causes Jekyll to regenerate repeatedly

### ISSUE THREAD

**Issue by smithtimmytim** [aarongustafson/jekyll-webmention_io#119]
Hello! I'm running Jekyll `3.8.5` and jekyll-webmention_io `3.3.2`. When I'm working on the site locally, something in this plugin is causing the site to continuously regenerate. I'm also using Jekyll's built-in livereload so the site just keeps refreshing. I've tried putting the webmention stuff behind `{% if jekyll.environment == "production" %}` but that doesn't seem to stop it.

Anyone else encounter this issue?

**Comment by aarongustafson** [comment]
Hmm, I have not seen this, but I don’t often do live reloading myself. I can look into it though.

**Comment by smithtimmytim** [comment]
Thanks so much! I tested yesterday without livereload and jekyll still regenerates when I haven't changed any files.

**Comment by aarongustafson** [comment]
@smithtimmytim Are you using `jekyll serve` for the live reload? I think I can turn it off if the site is serving.

**Comment by smithtimmytim** [comment]
@aarongustafson Thank you! I'll try this out in the next few days and report back :)

**Comment by smithtimmytim** [comment]
@aarongustafson Just tested this out. Unfortunately, looks like Jekyll continues to see changes happening in the `JekyllWebmentionIO.js` file.

```shell
Regenerating: 1 file(s) changed at 2018-12-14 11:28:39
                    js/JekyllWebmentionIO.js
[jekyll-webmention_io] Webmentions won’t be gathered when running `jekyll serve`.
[jekyll-webmention_io] Webmentions lookups are not run when running `jekyll serve`.
                    ...done in 3.075379 seconds.
```

That files seems to trigger regeneration indefinitely.

**Comment by aarongustafson** [comment]
Ok, I turned off JS source file generation while using `jekyll serve`. I think that should fix your issue, but if it does not, I will stop it from deploying a JavaScript file too.

**Comment by aarongustafson** [comment]
Actually, scratch that. I tweaked it so it falls back to the temp folder file generation now (rather than source). The deploy will happen, but does not appear to trigger regeneration.

**Comment by aarongustafson** [comment]
@smithtimmytim Can you confirm if this issue is resolved?

**Comment by smithtimmytim** [comment]
Oops! So sorry! I'll test this tonight and report back.

**Comment by smithtimmytim** [comment]
This issue is resolved. Looks like that fixed it!

**Comment by aarongustafson** [comment]
Yay!
