### ISSUE TITLE
Rake task will download entire file looking for webmention endpoint

### ISSUE THREAD

**Issue by alias1** [aarongustafson/jekyll-webmention_io#12]
While processing URLs, the rake task will download the entire file while looking for the webmention endpoint. On most html pages, this is fine, but it seems it will also download any arbitrary binary/etc links (eg zip files, pdf's, iso's, etc) that are linked from posts.

**Comment by aarongustafson** [comment]
Interesting. Any thoughts on how to avoid this? I suppose we could look at the MIME response in the header, but the file would still be captured. I could do a header request only, but then I would have to request the html file as well, adding additional time to the process. Another option would be to parse the URL and try to guess, but that’s also fraught with potential issues (assumptions, you know).

I’d love your thoughts on addressing this.

**Comment by alias1** [comment]
My original thought was the HEAD thing.. but the extra requests could be a pain.

The other idea I was having was just an arbitrary cutoff point, since the webmention should be in the head tags (from memory), it'd be unlikely that the head would be beyond 1/10/100kb for example. So while not an ideal solution, would prevent trying to pull down 100's of mb's of zip/iso/etc.

While it's sort of more annoying, I think ultimately the best solution might actually come from a combination of all 3. A size cutoff point (configurable with good default), a whitelist approach to file extensions (not ideal, but could catch some cases. might become obsolete with the file size limit though?), and then HEAD for anything that doesn't match the whitelist. Or something to that effect.

**Comment by aarongustafson** [comment]
Could incorporate this: https://github.com/indieweb/mention-client-ruby

**Comment by alias1** [comment]
That sounds awesome. I'm all for using standardised libraries where possible.

> This is accomplished by doing a HEAD request and looking at the headers for supported servers, if none are found, then it searches the body of the page.

Would have to check what they do for large files, but if it's still an issue probably better fixed as a PR there anyway, help more people :)

**Comment by aarongustafson** [comment]
I’ve implemented the webmention gem lookup in 2.3. It goes for the request header first, then grabs the document and selects the appropriate link element.

**Comment by alias1** [comment]
Sweet :)
