### ISSUE TITLE
bundle exec jekyll serve error

### ISSUE THREAD

**Issue by derpayatz** [aarongustafson/jekyll-webmention_io#127]
Hi, I am getting this when I execute `bundle exec jekyll serve`:

```
[jekyll-webmention_io] Webmentions won’t be gathered when running `jekyll serve`. 
jekyll 3.8.5 | Error:  undefined method `[]=' for nil:NilClass
```

**Comment by aarongustafson** [comment]
Can you run a trace? `bundle exec jekyll serve --trace` or `bundle exec jekyll build --trace`

That will give he a bit more to go on.

**Comment by gfrkorea** [comment]
I got the same error. build was successful. build trace show nothing useful.
although serve trace is as below.

`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
[jekyll-webmention_io] Webmentions won’t be gathered when running `jekyll serve`.
Traceback (most recent call last):
        19: from /usr/local/bundle/bin/jekyll:29:in `<main>'
        18: from /usr/local/bundle/bin/jekyll:29:in `load'
        17: from /usr/local/bundle/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
        16: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        15: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        14: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        13: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        12: from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        11: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        10: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `start'
         9: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `each'
         8: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `block in start'
         7: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
         6: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
         5: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
         4: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/site.rb:70:in `process'
         3: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/site.rb:173:in `generate'
         2: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/site.rb:173:in `each'
         1: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/site.rb:175:in `block in generate'
/usr/local/bundle/gems/jekyll-webmention_io-3.3.5/lib/jekyll/generators/gather_webmentions.rb:24:in `generate': undefined method `[]=' for nil:NilClass (NoMethodError)`

**Comment by gfrkorea** [comment]
I guess this issue is not due to webmention extension. I re-run same command that showed last error message. and it worked.

```
#!/bin/bash
export JEKYLL_VERSION=3.8.5
docker run --rm --name jekyll --volume="$PWD:/srv/jekyll" -p 3000:4000 -it jekyll/jekyll:$JEKYLL_VERSION jekyll serve --watch --drafts --trace
```

**Comment by aarongustafson** [comment]
::phew::
