### ISSUE TITLE
Syndincation to silo without clickable url

### ISSUE THREAD

**Issue by nysander** [aarongustafson/jekyll-webmention_io#133]
I saw this idea in tweets from tantek syndicated to twitter from its personal page.

urls are not urls at all for short thoughts etc. they are only text representation of text url like

so tweet contains "(example.com/XYZ)" text not the "(https://example.com/XYZ)" url. When you do not use popular shortener url text won't be automatically parsed to valid url and make linkable.

idea behind this is that when tweet contains whole message adding url to it which do not contain more context can be annoying for your readers.

this feature should be optional configurable globally for all content or per content category and then on particular post level override. 
Because making it calculated on post content lengths even though great idea could be to hard to code I think, if possible at all

maybe @fancypantalons you could make it possible? :)

**Comment by fancypantalons** [comment]
I believe you're referring to the debate around [permashortlinks](https://indieweb.org/permashortlink) and [permashortcitations](https://indieweb.org/permashortcitation).

It's definitely something I was contemplating recently.  Speaking for myself, I'm not sure I'd turn this on, as it seems it's pretty controversial.  In particular, these comments:

> You should NOT include a post permashortlink at the end of POSSE copies of notes that include the entire note. 

and:

> just fyi, PSCs never got much adoption, and it's not clear that they will ... i wouldn't encourage using them, but that's just my opinion - snarfed on IRC 2014-03-21 

led me to question whether it's something I want to do on my own POSSE'd posts.

That said, if there's interest in it, I could throw a PR together, maybe with support for reaching out to a url shortener as well.

**Comment by aarongustafson** [comment]
I have no strong opinion other than, if offered, outputting it should be optional and default to it **not** being included.

**Comment by nysander** [comment]
well for now you have posse source added to tweets that are created by brid.gy. And I saw in many short notes that they are clicked on twitter and then abandoned on my page. so for now it is a bit broken to me. 

Question is if this is just brid.gy fault or that could be changed on this plugin site what is syndicated to twitter / other silo

I will opt to (if ever) make this optional in post front matter and create default to not (with options to force adding permashortlink. I do not know if this is not the source to grab back web mentions likes from silo to our pages.

**Comment by fancypantalons** [comment]
> well for now you have posse source added to tweets that are created by brid.gy. And I saw in many short notes that they are clicked on twitter and then abandoned on my page. so for now it is a bit broken to me.

So are you saying the links on the POSSE'd copy (i.e. on twitter, github, etc) contain a *broken* link back to your site (that is, the link doesn't point to the right place) and so clicking it doesn't take people to your website?  Do you have an example?

Or am I misinterpreting what you're saying?

**Comment by fancypantalons** [comment]
So, couple follow-up comments on this one.  First, to handle URL shortening for my posts, I threw a plugin together here:

https://github.com/fancypantalons/jekyll-shortener

I'm using this plugin plus Apache and mod_rewrite, as documented in the plugin README, to generate short URLs on my own domain for all of my posts.

If I wanted that URL to show up in the POSSE'd copies sent via Brid.gy, I'd have to do two things:

1. Add the u-bridgy-omit-link class to my post to disable Brid.gy's default backlinking behaviour.
2. Make the short URL visible in whatever form I'd like through the post layout (maybe hiding it via CSS when viewing my website directly).

This way, when Brid.gy scrapes the post content for delivery to the syndication target, it would pick up the short URL in the note, and wouldn't include its own link.

**Comment by aarongustafson** [comment]
I kept having Ruby/Jekyll issues when upgrading my Mac, so I have moved off of Jekyll and will not be working on this project anymore, going forward. I am going to flag this as won’t fix, but leave it open in case someone else wants to pick up the project from here.

**Comment by fancypantalons** [comment]
Closing this issue as I don't think there's anything to do in this plugin, as the requested behaviour can be controlled via brid.gy and the user's site templates.
