### ISSUE TITLE
Update webmention dependency from 0.1.6 to latest (v5.0.0)

### ISSUE THREAD

**Issue by 0xdevalias** [aarongustafson/jekyll-webmention_io#138]
Currently this plugin depends on an old version of the `webmention` gem (`0.1.6`), which is now up to `3.0.0`.

- https://github.com/aarongustafson/jekyll-webmention_io/blob/master/jekyll-webmention_io.gemspec#L47
  - `s.add_runtime_dependency "webmention", "~> 0.1.6"`
- https://github.com/indieweb/webmention-client-ruby/releases
  - breaking changes at v1.0

**Comment by cgorshing** [comment]
Now the webmention ruby gem is at 4.0 https://github.com/indieweb/webmention-client-ruby/releases

**Comment by aarongustafson** [comment]
I kept having Ruby/Jekyll issues when upgrading my Mac, so I have moved off of Jekyll and will not be working on this project anymore, going forward. I am going to flag this as won’t fix, but leave it open in case someone else wants to pick up the project from here.

**Comment by cgorshing** [comment]
I'd be interested in helping wit this as I'm currently using it.

**Comment by fancypantalons** [comment]
@cgorshing Do you already have a draft of the necessary changes available that you could use to open a PR?  I've been added as a contributor on the project and can work with you to merge them in.

**Comment by fancypantalons** [comment]
I've created a PR for this but I haven't had a chance to throughly test it yet.  The changes are small enough that I think it's in good shape, but if anyone could give this PR a shot, that'd be very helpful!

**Comment by fancypantalons** [comment]
Well, irony of ironies, the Webmention client moved to explicitly *not* allowing Ruby 3 back in June of 2018, which means that if I upgrade the Webmention dependency, we lose the ability to run on Ruby 3.  For now I'm going to hold this PR and hopefully the Webmention gem will get updated...

**Comment by cgorshing** [comment]
@fancypantalons -> https://github.com/indieweb/webmention-client-ruby/commit/a31aae69b176a681d965976a44b9c900847c1c42 😄

**Comment by fancypantalons** [comment]
It doesn't look like they've published a new version of the gem, but this is good progress!  Just gotta wait, now...

**Comment by fancypantalons** [comment]
It's been some year... alright... finally getting back to this.

I've pushed this change to main.  I've done some basic smoke testing but it deserves some more validation before I close the issue.

**Comment by fancypantalons** [comment]
Pushed 3.3.7 which upgrades the dependency to 7.0.0.
