### ISSUE TITLE
Unable to run on Jekyll 4

### ISSUE THREAD

**Issue by stevenjmesser** [aarongustafson/jekyll-webmention_io#139]
https://github.com/aarongustafson/jekyll-webmention_io/blob/8a9e5a199df899490a93782796124105eda21660/jekyll-webmention_io.gemspec#L41

Is it possible to update the dependencies so that this can be used with Jekyll 4?

**Comment by cgorshing** [comment]
A good discussion is happening on https://github.com/aarongustafson/jekyll-webmention_io/issues/130 discussing this. You might find it valuable.

**Comment by stevenjmesser** [comment]
Thanks @cgorshing, I'll close this issue as it's clearly a duplicate. Wish I'd spotted that before!
