### ISSUE TITLE
Documentation link returns 404

### ISSUE THREAD

**Issue by kevquirk** [aarongustafson/jekyll-webmention_io#145]
The "read the docs" link in read me returns a 404. Has the documentation been deleted?

Link: https://aarongustafson.github.io/jekyll-webmention_io/

**Comment by Geo25rey** [comment]
Docs are still available in docs folder in the repo. It's just links are broken

**Comment by aarongustafson** [comment]
I think this happened when I changed the primary branch name to "main." It shoudl revsolve in a few minutes.
