### ISSUE TITLE
Error Checking if wm.io down

### ISSUE THREAD

**Issue by miklb** [aarongustafson/jekyll-webmention_io#15]
Just ran into an issue where webmention.io is currently down, throwing a 502 error, stopping jekyll build in its tracks.

Wondering if there is a way to bail on checking for webmentions in that scenario?

**Comment by aarongustafson** [comment]
Seems doable. I think I added similar checks on other URL polling. I’m putting together a talk for the week after next and will be traveling for conferences over the next two weeks, but I will see if I can slip it in quickly.

**Comment by miklb** [comment]
Cool. Aaron fixed the 502 error on the site this morning and don't anticipate anything being down for a long period, but worth having on radar since it breaks the build. 

Thanks as always for the plugin.

**Comment by aarongustafson** [comment]
Bad URL caching (with a configurable cache duration) is in the gem release.
