### ISSUE TITLE
Suggestion on Storing Webmention Response?

### ISSUE THREAD

**Issue by miklb** [aarongustafson/jekyll-webmention_io#16]
In a perfect world, syndicated posts (i.e. notes POSSE'd to Twitter) should have a `rel-syndication` link [IndieWeb - rel-syndication](https://indieweb.org/rel-syndication).

I realize that a webmention can't be sent until after the post is generated, so for what I want to do, which may be out of the scope of this plugin, is store the the syndication link as Front Matter and generate a new build to display.

What I'm hoping is you might have a pointer as to how to retrieve the response from bridgy in the rake task that sends the mention so I could then add that as Front Matter and deal with the update in my build/deploy work flow.

**Comment by miklb** [comment]
I decided to replace the `curl` with a `net/http` call
```
uri = URI("#{endpoint_url}")
response = Net::HTTP.post_form(uri, 'target' => "#{target}", 'source' => "#{source}")
```
And I think I'm going to a check for the response code and then dump the response into a `_data` file so the whole object is available to use.

Curious if a similar approach could be taken for received webmentions, that is, stored in a data file so  user could have more flexibility in the markup, and more data portability with webmention.

Thoughts?

**Comment by aarongustafson** [comment]
This is part of the overhaul I am in the process of doing right now. You’ll be able to create your own markup templates and get webmentions in aggregate or in collections of likes, reposts, etc.

**Comment by martymcguire** [comment]
I haven't packaged it up for release, yet, but I made a similar plugin that fetches and caches incoming webmentions in `_data` keyed by source+target to reduce duplication, but also indexed by post so looking up "mentions for this post" is pretty trivial.

Some of it is probably pretty specific to my site layout, but might be useful to crib from??

**Comment by aarongustafson** [comment]
Great! This one already does that too. It's not in data, though that would
be trivial to do as the cache location is configurable ;-)

**Comment by aarongustafson** [comment]
> I haven't packaged it up for release, yet, but I made a similar plugin that fetches and caches incoming webmentions in _data keyed by source+target to reduce duplication, but also indexed by post so looking up "mentions for this post" is pretty trivial.

I just updated the docs (and the gem). Take a look. Everything is structured as true YAML data so you can do totally custom templates (per tag!) if you want.

In terms of POSSE-ing your content, this gem is not doing that… yet.

I’m going to close out this bug and add an enhancement request for storing responses to webmentions that have been made. Those webmentions are tracked (so we don’t make the same one twice), but no data about thew response is stored at this time.
