### ISSUE TITLE
Webmentions are not received

### ISSUE THREAD

**Issue by xplosionmind** [aarongustafson/jekyll-webmention_io#162]
I believe to have correctly configured the plugin, still, at build time my website receives none.

Firstly, here is the proof that the test webmention was succesfully sent:
<img width="935" alt="Screenshot 2021-11-22 at 3 51 51 PM" src="https://user-images.githubusercontent.com/42862428/142883130-7551c2a2-20d5-4c62-bf9a-be76f8edb483.png">

[Here](https://github.com/xplosionmind/tommi.space/blob/72d181aed29c5eaaaca59d436cb010886a32ee21/_includes/comments.html#L18) you can find my code which should parse the Webmentions sent as the picture above shows, but instead I get this (see [here](https://web.archive.org/web/20211122145712/https://tommi.space/cft#webmentions)):
<img width="719" alt="Screenshot 2021-11-22 at 3 57 38 PM" src="https://user-images.githubusercontent.com/42862428/142884327-4ef02b1b-7cd9-4e9f-9c4b-19b85cf32bc0.png">

What am I doing wrong? Or is it a bug?

**UPDATE**: The Webmentions have been sent before the website deployment.

**Comment by fancypantalons** [comment]
Are they present in `webmention_io_received.yml` in the cache directory?

**Comment by xplosionmind** [comment]
> Are they present in `webmention_io_received.yml` in the cache directory?

They are not for `/cft`, which is the article in question. Nevertheless, by looking at that file I discovered that I am retrieving them for [this post](https://tommi.space/non-sono-abbastanza#webmentions '“Non sono abbastanza„ on tommi.space'), for instance. So it does not appear to be a global problem.

**Comment by xplosionmind** [comment]
I just thought about this: could it be a problem related to the webmention coming from the same domain of the destination?

Anyways, I am puzzled because I triggered the webmention from <https://indiewebify.me>, and I got a “success” message.

**Comment by fancypantalons** [comment]
So what does the `webmentions` configuration block look like?  The plugin will by default *only* process posts (i.e. files in _posts) unless you enable processing of pages using the `pages` configuration directive.

**Comment by xplosionmind** [comment]
> The plugin will by default _only_ process posts

It is a post… Since in the in other pages I receive webmentions, I am starting to think that it is a problem of <https://webmentions.io>

**Comment by fancypantalons** [comment]
Can you set `debug: true` in your webmentions block, as follows:

```yaml
webmentions:
  ...
  debug: true
  ...
```

Then:

1. Delete `.jekyll-cache/webmention_io_lookups.yml` (this ensures lookup throttling isn't stopping the plugging from making a request to webmention.io)
2. Run a `jekyll build`
3. Run a `jekyll webmention`

Then post the output from steps 3 and 4?

This will allow us to determine if the plugin is attempting to retrieve webmentions for the affected URLs, and if so, might provide some telemetry to see what's going on.

**Comment by fancypantalons** [comment]
Can you set `debug: true` in your webmentions block, as follows:

```yaml
webmentions:
  ...
  debug: true
  ...
```

Then:

1. Delete `.jekyll-cache/webmention_io_lookups.yml` (this ensures lookup throttling isn't stopping the plugging from making a request to webmention.io)
2. Run a `jekyll build`
3. Run a `jekyll webmention`

Then post the output from steps 3 and 4?

This will allow us to determine if the plugin is attempting to retrieve webmentions for the affected URLs, and if so, might provide some telemetry to see what's going on.

**Comment by xplosionmind** [comment]
> Then post the output from steps 3 and 4?

Sure. Outputs are quite long, though. [Output of 3 is here](https://paste.yunohost.org/raw/uyimocimiq) and [output of 4 is here](https://paste.yunohost.org/raw/qusowubozi).

I am sure that the link to `pixelfed.com` is formatted correctly. One strange thing, though: I modified all links which were `pixelfed.com` to `pixelfed.org`, but—even after deleting all of `.jekyll-cache`— I still see `.com` in the error, not `.org`. I am sure there is no `pixelfed.com` link anywhere on my website

**Comment by fancypantalons** [comment]
Honestly, I'm starting to think if this is an issue in webmention.io itself.  Manually hitting just this URL:

```
https://webmention.io/api/mentions?target[]=https://tommi.space/cft
```

Should return webmentions, based on the screenshot of the dashboard you showed.  And yet it returns no results.

By contrast, if I replace that URL with a page on my own blog that has webmentions, it works fine.

**Comment by aarongustafson** [comment]
I was gonna suggest reaching out to @aaronpk, so I'm glad you filed the issue. He's been quite responsive and helpful in resolving issues I've encountered in the past (which, frankly, usually ended up being my fault).

**Comment by fancypantalons** [comment]
Judging by #178 being closed, I'll close this as well.
