### ISSUE TITLE
Jekyll 3.3 breaks webmention caching

### ISSUE THREAD

**Issue by miklb** [aarongustafson/jekyll-webmention_io#17]
I haven't dug into it yet, but I suspect the changes to `site.url` and local dev  - [Jekyll 3.3 release](http://jekyllrb.com/news/2016/10/06/jekyll-3-3-is-here/) are at play.

Running `jekyll serve` locally changed the `webmentions.yml` file to use `http://localhost:4000` instead of the my domain url. If I find a fix I'll send a pull request or update this issue since my fork is fairly customized at this point.

Cheers.

**Comment by miklb** [comment]
Following up, this was specific to using `jekyll serve` locally, and apparently it was a design decision to hijack the `site.url` for serving locally unless you set the `JEKYLL_ENV` to something other than `development` (the default) when serving the site. Seems like a heavy handed approach to me.

So to summarize, if you don't want your cache file to be overwritten with `localhost:4000` for your source links in `.cache/webmentions.yml` when serving locally, you must set the environment to something other than `development`

**Comment by aarongustafson** [comment]
If `site.url` gets updated, does the actual `config` variable? If not, I may be able to tweak it to reference the original config value instead.

I haven’t moved to Jekyll 3 yet, so I have not been able to test myself.

**Comment by aarongustafson** [comment]
Flagging this to avoid sending webmentions if the site is serving (as opposed to building).

```
config['serving']
```

**Comment by aarongustafson** [comment]
Actually, looking back, I revised this to make sending a jekyll command. Closing this since it will be a manual thing (or part of your build process).
