### ISSUE TITLE
Webmention content shouldn't be passed through markdown parser

### ISSUE THREAD

**Issue by fancypantalons** [aarongustafson/jekyll-webmention_io#170]
Looking through the specs and the behaviour of webmention.io, it sure looks to me like that content we receive in a webmention is going to be either stripped text or sanitized HTML, but *not* Markdown.  For example, the IndieWeb wiki covering displaying comments doesn't talk about rendering content this way:

https://indieweb.org/comments#How_to_display

Additionally, [this issue](https://github.com/aaronpk/webmention.io/issues/13)  as well as various examples I've come across lead me to believe webmention.io is passing sanitized HTML back.

As a result, I believe it's best to remove the code that automatically passes the webmention content through a markdown parser and instead leave that to the users, who can always do the same thing in their templates.

**Comment by aarongustafson** [comment]
Sounds good. The API improvements will make the Jekyll parsing much faster now.
