### ISSUE TITLE
Webmention showing up on wrong page.

### ISSUE THREAD

**Issue by krusynth** [aarongustafson/jekyll-webmention_io#179]
Hi there, I have very few webmentions on my site, I have one webmention showing up on multiple post pages, but only one of them is the correct page. It looks like when the tag is rendered, the class data is not being cleared out from the instance, which means that if a webmention is found on a previous page, it will then be show on every subsequent rendered page if there is no match in the cached data.

[This is the line where the data is being set](https://github.com/aarongustafson/jekyll-webmention_io/blob/fc0102981353bbc644f5c5e7f76deb43d9295584/lib/jekyll/tags/webmention.rb#L101), and adding `set_data([], [])` on line 65 seems to fix this for me without side effects.

To reproduce: create a new post on your blog, *after* a post that has a webmention. Do not refresh your cached mentions and simply serve the page. The new post should show the webmention from the previous post.

**Comment by fancypantalons** [comment]
Apologies for the delay in responding!

Yup, the code was clearly failing to set the tag state on every page render call, which would cause old stale state to be used in some circumstances.

I've pushed a commit to address the bug. Take a look at let me know if it resolves the behaviour on your end!

**Comment by krusynth** [comment]
Delay?? That was wicked fast!  This works perfectly for me :shipit: !  Thank you so much for the very quick fix!
