### ISSUE TITLE
Error:  incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#18]
When I add `{%webmentions <my URL> %}` to my `_layouts/post.html` template and run `bundle exec jekyll build`, I get the following error:

```
Liquid Exception: incompatible character encodings: UTF-8 and ASCII-8BIT in /_layouts/post.html
jekyll 3.3.1 | Error:  incompatible character encodings: UTF-8 and ASCII-8BIT
```

**Comment by aarongustafson** [comment]
I just ran into this the other day too. I will check in the fix that seems to be working for me.

**Comment by nhoizey** [comment]
Great!

**Comment by aarongustafson** [comment]
Pushed. Commit c9cfb36. Updated the Js a bit in the follow-up commit too.
