### ISSUE TITLE
Add parameters to only display webmentions of a certain type

### ISSUE THREAD

**Issue by lewisnyman** [aarongustafson/jekyll-webmention_io#2]
After reading http://indiewebcamp.com/comments-presentation#How_to_display I think that this plugin would become more useful if I were able to separately display replies and shares from just mentions. At the moment I can only display them all together

**Comment by aarongustafson** [comment]
That’s a cool idea. I’ll give it some thought and see what I can do. Or if you want to take a stab at it, feel free to submit a PR. It would probably be best to add new tags for the separated views. Or they could be params on the tag. Not sure which would be best/easier.

**Comment by lewisnyman** [comment]
I think I can give it a go. I'll need this on my site anyway. I'll have a look at the code and decide how tricky  it would be to split this into separate functions.

**Comment by aarongustafson** [comment]
This is in the forthcoming gem. Here’s a sample of what you’ll have:

```
<p>Total webmentions: {% webmention_count page.url %}</p>

<p>Total likes: {% webmention_count page.url likes %}</p>

<h2>All</h2>
{% webmentions page.url %}

<h2>Replies &amp; Posts</h2>
{% webmentions page.url replies posts %}

<h2>Links</h2>
{% webmention_links page.url %}

<h2>Likes</h2>
{% webmention_likes page.url %}

<h2>Replies</h2>
{% webmention_replies page.url %}

<h2>Reposts</h2>
{% webmention_reposts page.url %}
```
