### ISSUE TITLE
Optimize avatars

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#24]
Avatars provided by webmention.io can be really heavy, like [this one](https://s3-us-west-2.amazonaws.com/ca3db/twitter.com/157a8e9c1212a9506cc12c2cc7013889236e35667ba1444b7343ce6f69928ad9.jpeg) used [here](https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html#webmentions):

<img width="954" alt="image" src="https://user-images.githubusercontent.com/78213/27474035-5af8f614-5801-11e7-81d9-c2ad5f82892f.png">

It would be great to be able to get a reduced and optimized copy of each avatar in the local site.

It would also make the site less dependent on webmention.io availability and performance.

Issue identified thanks to Cloudinary's new tool: https://webspeedtest.cloudinary.com/ (+@eeeps)

**Comment by aarongustafson** [comment]
Yes! I'm the new gem-based version I noticed the sizes are way out of whack
(as in wildly inconsistent). I've been thinking about it but need to fix my
get issues first. I agree Cloudinary could be good. Or one of the other
offerings that don't require an account. Config option proposals welcome!

**Comment by nhoizey** [comment]
There might be an elegant way to deal with this: #25

**Comment by aarongustafson** [comment]
I am going to close this as I believe the custom template option should be enough to handle it. If it’s not—which I can only imagine would be if there’s something else I need to handle in the Liquid parser for the templates—I can re-open this bug.

**Comment by nhoizey** [comment]
I agree.

**Comment by nhoizey** [comment]
And so, it did help, thanks!

https://nicolas-hoizey.com/2017/07/so-long-disqus-hello-webmentions.html#august-11th-2017-update

**Comment by aarongustafson** [comment]
Yay!

**Comment by nhoizey** [comment]
;-)
