### ISSUE TITLE
Publish to rubygems.org

### ISSUE THREAD

**Issue by lewisnyman** [aarongustafson/jekyll-webmention_io#3]
If [we publish this](http://guides.rubygems.org/publishing/) then it becomes a lot simpler to find, [install,](http://jekyllrb.com/docs/plugins/) and contribute back to. The only way to use it right now is to copy it into the plugins directory which tends to encourage the behaviour of copying and editing instead of posting PRs.

What do you think?

**Comment by aarongustafson** [comment]
Good idea. I have not published anything to RubyGems before, but I will look into the process.

**Comment by aarongustafson** [comment]
I’m not clear: how would I bundle the JS and rakefile with this as a Gem? The JS I could always expose via a Jekyll tag, so that isn’t as big of a deal, but I’m not sure the convention for supplementary stuff like this, especially the Rake task.

**Comment by lewisnyman** [comment]
I'm no expert in this either, maybe we could it a go with just the liquid tag and then add to it? I've published a compass extension as a gem before, but that was using this yeoman setup https://github.com/at-import/generator-compass-extension

**Comment by lewisnyman** [comment]
This might help https://github.com/jekyll/jekyll-test-gem-plugin

**Comment by alias1** [comment]
+1, definitely interested in this as a gem.

Just made a similar PR for indirect/jekyll-postfiles#7 which was mostly generated using `bundler gem jekyll-postfiles` with a few tweaks afterwards.

One thing that I had to do was change the `jekyll/postfiles` folder structure to just `jekyll-postfiles`, otherwise loading through the config file doesn't match other plugins like [jekyll/jekyll-feed](https://github.com/jekyll/jekyll-feed)

**Comment by alias1** [comment]
This is still definitely a thing i'd be keen on! Any chance you'll have the time to do it? Or if not, got some pointers how you'd want it done, open to PR's?

**Comment by aarongustafson** [comment]
I started working on it and got frustrated when trying to figure out how to
bundle the JavaScript for live updating and the rake tasks. I did port the
Crosspost to Medium one :-)

**Comment by alias1** [comment]
I saw that :) (just installed it)
Hrmm, that's annoying. What aspect of the JS was tripping you up?

Sent from Outlook Mobile




On Tue, Apr 12, 2016 at 7:28 AM -0700, "Aaron Gustafson" <notifications@github.com> wrote:










I started working on it and got frustrated when trying to figure out how to

bundle the JavaScript for live updating and the rake tasks. I did port the

Crosspost to Medium one :-)

**Comment by aarongustafson** [comment]
How to properly bundle it in the Gem and the best way to expose it back to
Jekyll.

On Tuesday, April 12, 2016, alias1 <notifications@github.com> wrote:

> I saw that :) (just installed it)
> Hrmm, that's annoying. What aspect of the JS was tripping you up?
>
> Sent from Outlook Mobile
>
>
>
>
> On Tue, Apr 12, 2016 at 7:28 AM -0700, "Aaron Gustafson" <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>
>
>
>
>
>
>
>
>
> I started working on it and got frustrated when trying to figure out how to
>
> bundle the JavaScript for live updating and the rake tasks. I did port the
>
> Crosspost to Medium one :-)
>
>
>
> On Tue, Apr 12, 2016 at 12:58 AM, alias1 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>
>
> > This is still definitely a thing i'd be keen on! Any chance you'll have
>
> > the time to do it? Or if not, got some pointers how you'd want it done,
>
> > open to PR's?
>
> >
>
> > —
>
> > You are receiving this because you commented.
>
> > Reply to this email directly or view it on GitHub
>
> > <
> https://github.com/aarongustafson/jekyll-webmention_io/issues/3#issuecomment-208706226
> >
>
> >
>
>
>
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
>
>
>
>
>
>
>
>
>
>
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/aarongustafson/jekyll-webmention_io/issues/3#issuecomment-209033159>
>


-- 
Cheers,

Aaron

**Comment by alias1** [comment]
So reading over the type of plugins, the 2 that sound potentially useful for exposing the JS to me would be [generators](https://jekyllrb.com/docs/plugins/#generators) (most likely) or hooks.

If we had a generator that reads the contents of the JS file from the gem and makes a new [Jekyll::StaticFile](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/static_file.rb), outputting it to a location controlled from the site config, that could probably work?

Then a tag for loading the JS file from the same path that we output it to.

What do you think?

Also, I started hacking together (haven't touched ruby in ages) a tag for the webmention/pingback header tags (and looking to do one for redirected_from as well once I figure out how it works)

```
  class WebmentionHeaderTag < Liquid::Tag
    @@warned = {}

    def initialize(tag_name, text, tokens)
      super
      # @text = text
    end

    def render(context)
      site = context.registers[:site]

      if site.config['jekyll-webmention-io']
        @config = site.config['jekyll-webmention-io']
      else
        if !@@warned.has_key?('config')
          Jekyll.logger.warn "jekyll-webmention-io:", "_config.yml key not defined: jekyll-webmention-io"
          @@warned['config'] = true
        end

        return ""
      end

      if @config.has_key?('domain')
        @domain = @config['domain']
      else
        if !@@warned.has_key?('domain')
          Jekyll.logger.warn "jekyll-webmention-io:", "_config.yml key not defined: jekyll-webmention-io.domain"
          @@warned['domain'] = true
        end

        return ""
      end

      out = ""

      if @domain
        out += "<link rel=\"webmention\" href=\"https://webmention.io/#{@domain}/webmention\" />\n"
        out += "<link rel=\"pingback\" href=\"https://webmention.io/#{@domain}/xmlrpc\" />\n"
      end

      return out
    end
  end
```

Not sure of a nicer/less verbose way of doing those config key checks, but if there is one, would simplify this down a lot.

**Comment by alias1** [comment]
Started working on the [conversion to gem](https://github.com/alias1/jekyll-webmention_io/tree/convert-to-gem) on my fork. Will see if I can get the above JS loading idea working.

**Comment by alias1** [comment]
Got the JS file from gem -> built site working with a generator.

Still need to create the JS liquid tag and convert the rake task to a jekyll command.

**Comment by alias1** [comment]
Just created a PR for this @aarongustafson @lewisnyman 

Mostly tested with Jekyll 3.x

Let me know what you think.

**Comment by alias1** [comment]
Heya, Just wondering if you'd had a chance to check the PR out yet?

**Comment by aarongustafson** [comment]
I’m sorry I have not had much of a chance to tuck into it yet. I’m prepping
to give a talk at SpeechTek next week and am also solo-parenting my
5-month-old right now while my wife is at another conference :-/

I should have some time toward the end of next week. I sincerely apologize
for the delay.

**Comment by alias1** [comment]
Eep, business! No stress, just wanted to make sure it didn't get forgotten about :)

Get Outlook for iOS




On Wed, May 18, 2016 at 7:42 AM -0700, "Aaron Gustafson" <notifications@github.com> wrote:










I’m sorry I have not had much of a chance to tuck into it yet. I’m prepping

to give a talk at SpeechTek next week and am also solo-parenting my

5-month-old right now while my wife is at another conference :-/



I should have some time toward the end of next week. I sincerely apologize

for the delay.

**Comment by aarongustafson** [comment]
Still tracking this, I‘m sorry I have been so quiet. I will review soon, I promise!

**Comment by alias1** [comment]
That's alright. I know the feels when life gets crazy. Let me know if there's anything I can do to help get it merged.

**Comment by aarongustafson** [comment]
Just an update: The move to a gem is in progress.

**Comment by alias1** [comment]
Woohoo!!

**Comment by aarongustafson** [comment]
You can preview here: https://github.com/aarongustafson/jekyll-webmention_io/tree/gem_conversion
