### ISSUE TITLE
Store response data from sent webmentions

### ISSUE THREAD

**Issue by aarongustafson** [aarongustafson/jekyll-webmention_io#30]
This bubbled up in #16. Should be easy enough.

It might also make sense to combine the (currently)  two separate "outgoing" & "sent" webmentions files and track all of the details in one spot (as opposed ot having to work across two files.

**Comment by aarongustafson** [comment]
Integrating the webmention gem allows for this more easily. To make it happen thought, I need to do a few things:

- [ ] Write a sent webmentions migration script
- [ ] Figure out the best way to store responses
- [ ] Implement the change

**Comment by aarongustafson** [comment]
@miklb @martymcguire Are you just looking for me to store the response body or do you want headers and such too?

**Comment by miklb** [comment]
@aarongustafson  For me the response body would be enough.

**Comment by martymcguire** [comment]
Same. There is a possible use case for storing HTTP result codes if there
is an error fetching the content, but I don't currently try to use it, so
🤷‍♂️

**Comment by miklb** [comment]
agreed the response code would be handy for debugging.

**Comment by aarongustafson** [comment]
So… assuming there’s not an location or server error, the response should provide an error object in the JSON, so that would get passed into the response body. The way I have things set up (and the way the webmentions gem processes the response), any failure will result in a `false` return. I currently have a `false` value as the default state that indicates a URL has not been mentioned. Storing false after a failed webmention would essentially keep it alive for the next run of the command. That sound good?

Here’s a look at the new, combined, format for outgoing webmentions with 3 failed webmentions and one success:

```yml
---
https://www.aaron-gustafson.com/jekyll/update/2017/06/20/welcome-to-jekyll.html:
  https://jekyllrb.com/docs/home: false
  https://github.com/jekyll/jekyll: false
  https://talk.jekyllrb.com/: false
  http://webmention.io/:
    status: queued
    summary: Webmention was queued for processing
    location: https://webmention.io/pingback/webmention/fZm5CkgNN6yuFWnc9NXw
    source: https://www.aaron-gustafson.com/jekyll/update/2017/06/20/welcome-to-jekyll.html
    target: http://webmention.io/
```

That work for you all?

**Comment by aarongustafson** [comment]
It’s worth noting that, for legacy purposes, I am adding a function to upgrade from the old two-file setup (queued and sent) to the combined file. For any webmentions that have been sent prior to the upgrade, I was planning to have the value be an empty string `""`. Any thoughts on that?

**Comment by aarongustafson** [comment]
> agreed the response code would be handy for debugging.

I have some logs running during the build to let you know what’s going on:

```bash
[jekyll-webmention_io] Looking for webmention endpoint at https://jekyllrb.com/docs/home
[jekyll-webmention_io] No webmention endpoint at https://jekyllrb.com/docs/home
[jekyll-webmention_io] Looking for webmention endpoint at https://github.com/jekyll/jekyll
[jekyll-webmention_io] No webmention endpoint at https://github.com/jekyll/jekyll
[jekyll-webmention_io] Looking for webmention endpoint at https://talk.jekyllrb.com/
[jekyll-webmention_io] No webmention endpoint at https://talk.jekyllrb.com/
[jekyll-webmention_io] Looking for webmention endpoint at http://webmention.io/
[jekyll-webmention_io] Sending webmention of http://webmention.io/ in https://www.aaron-gustafson.com/
jekyll/update/2017/06/20/welcome-to-jekyll.html to https://webmention.io/pingback/webmention
```

I will likely slim these down for production and limit it to successes and failures an webmentioning only rather than reporting missing endpoints and such.

**Comment by miklb** [comment]
👍

I recall seeing the logging commented out in the old plugin, was helpful for me when I was debugging some things.

Here's an example of how I was dumping a raw response from bridgy [to a json data file](https://github.com/miklb/miklb.github.com/blob/jekyll/_data/10384.json) so your example definitely looks cleaner. My hacked together [Rakefile](https://github.com/miklb/miklb.github.com/blob/jekyll/Rakefile#L42) that generated that.

Mind you I switched away from Jekyll about 6 months ago, but intend to pick it back up for a new site soon, so will be able to dig in more.

Can't thank you enough for picking this back up and putting in so much work to create the gem.
