### ISSUE TITLE
Would you like to configure how often the plugin looks for webmentions?

### ISSUE THREAD

**Issue by aarongustafson** [aarongustafson/jekyll-webmention_io#31]
Just wondering if it might be useful for speeding things up when you are debugging a build. Could be a configuration option like `skip_webmention_collection_for` and take a number of days as an argument.

**Comment by miklb** [comment]
I think that would be useful, and if I'm reading correctly, an option would be to only check for webmentions for last X days? A 12 year old blog with some crufty links from the early days don't really need to be checked in my own anecdotal experience.

**Comment by aarongustafson** [comment]
Actually I was thinking about pausing all lookups for a period of time. It
might be possible to add some advanced config down the line to check older
posts less frequently. Something like

```
webmentions:
  throttles:
    last_year: daily
    older: monthly
```

It’s possible. It’d be interesting to see if folks would be interested in
that.

**Comment by aarongustafson** [comment]
Actually I was thinking about pausing all lookups for a period of time. It
might be possible to add some advanced config down the line to check older
posts less frequently. Something like

```yml
webmentions:
  throttles:
    last_year: daily
    older: monthly
```

It’s possible. It’d be interesting to see if folks would be interested in
that.

**Comment by miklb** [comment]
> Actually I was thinking about pausing all lookups for a period of time
👍 definitely would be nice for local dev. 

My build times had gotten really long & I was basically attributing it to all the links/posts it was checking. I'm about to do another Jekyll site for small project and look forward to testing out the new gem. Thanks for all the work on it.

**Comment by aarongustafson** [comment]
I went ahead and added the basic pause in 2.1.0: https://github.com/aarongustafson/jekyll-webmention_io#pausing-lookups

**Comment by alias1** [comment]
I'd like throw a +1 in for 'don't do older posts'. Even if it's just a really simple thing like "don't check before date X"

**Comment by aarongustafson** [comment]
You do run the risk of losing stuff @ that point though. Plus, FWIW, I’ve
implemented `since_id` in the queries to webmention.io, so the script will
have a reduced amount of processing to do (which will speed it up immensely
as before it was re-processing a constantly growing list of mentions).

**Comment by alias1** [comment]
Hrmm, that's fair. I guess my use case was that if it's an old post from like 2003 or something I don't know if I care. But that's probably not entirely true now that I think about it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aarongustafson** [comment]
I am going to begin working on this, but just an FYI: I have implemented `since_id` with webmention.io in PR #38, so the processing time should be greatly reduced now.

**Comment by aarongustafson** [comment]
I am working on this feature right now. First pass is in [the `throttle_lookups` branch](https://github.com/aarongustafson/jekyll-webmention_io/tree/throttle_lookups). I am traveling right now and don't have my usual laptop with me, so I need to wait to get home to test, but if you'd like to beta it, feel free. Here are the `_config.yml` options:

* `throttle_lookups` - hash for the config
* Timeframes: `last_week`, `last_month`, `last_year`, `older`
* Supported values: daily | weekly | monthly | yearly | every X day/week/month/year(s) 

This should let you get crazy granular:

```yml
webmentions:
  throttle_lookups:
    last_week: daily
    last_month: weekly
    last_year: every 2 weeks
    older: monthly
```

If you get a chance to try it out, I have the logging on by default right now so we can see if it is working as expected. I should be able to test it within Jekyll by Monday at the latest.

**Comment by aarongustafson** [comment]
Sorry for the delay. I’ve run it through the test site and so far so good. Gonna try it on my own site now.

**Comment by aarongustafson** [comment]
Looks good and damn does it speed things up! I’ll add the details to the docs and bump to 2.7.0.

**Comment by alias1** [comment]
Sounds great! Haven't touched my blog for a bit, but might get a chance this weekend so will try it then :)
