### ISSUE TITLE
Quickstart guide in readme?

### ISSUE THREAD

**Issue by alias1** [aarongustafson/jekyll-webmention_io#39]
Reading through the whole readme (with knowledge of how most of it works) there is enough info to get things going, but it might be useful to have a tiny little quickstart, like:

* Add `gem 'jekyll-webmention_io'` to Gemfile
* Add plugin to `gems` section of _config.yml
* `bundle install`
* Add X tag to headers
* Add Y tag to body
* Add x tag to post template
* etc

**Comment by aarongustafson** [comment]
Done!

**Comment by alias1** [comment]
Awesome, thanks :)
