### ISSUE TITLE
JekyllWebmentionIO.js, why source folder?

### ISSUE THREAD

**Issue by alias1** [aarongustafson/jekyll-webmention_io#41]
Just curious, why're you generating the `JekyllWebmentionIO.js` into the source folder? I think in my original gem version (would have to check), I used a generator to just make it go straight into the 'build' folder when the site is generated. No need to clutter up the source that way.

See: https://github.com/alias1/jekyll-webmention_io/blob/convert-to-gem/lib/jekyll-webmention-io/webmention_js_generator.rb

**Comment by aarongustafson** [comment]
The reason I did that was to enable folks to modify the JS source if they wanted to. I can make it configurable if you would like. Maybe by setting `js.destination` to `false`?

**Comment by alias1** [comment]
That makes sense. Yeah, the ability to have it automagically pass through would be good for me.

What would be a usecase for needing to modify it manually?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aarongustafson** [comment]
I will look into the pass-through. Manual modification might be necessary if you use a custom HTML template and need to tweak the JS. After publishing & modifying it, you’d want to turn off the auto-build.

Mostly it’s for tools like Webpack, Gulp & Grunt though.

**Comment by alias1** [comment]
That makes sense

**Comment by aarongustafson** [comment]
Ok, I tried to make it work and in order to get Jekyll to load the static file into the destination folder as part of the Jekyll build, the file needs to exist in the source folder. I tried making it work without it and I also tried removing the file after processing and neither worked (Ruby errors). Sorry, but it looks like you’re going to have to live with a file being output.

That said, [you can totally configure where it’s going to be put](https://github.com/aarongustafson/jekyll-webmention_io#the-javascript-file).

**Comment by alias1** [comment]
Did you look at static file generators and the code I used in my original gem version? My version reads the file from the gem source and writes it into the built site, no need to exist in the source.

Can link/copy the code here if you need (or just look at the gem branch on my fork of this project)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aarongustafson** [comment]
I'll take a look.

**Comment by alias1** [comment]
Link for reference (also at the top of this thread): https://github.com/alias1/jekyll-webmention_io/blob/convert-to-gem/lib/jekyll-webmention-io/webmention_js_generator.rb

And the relevant docs: https://jekyllrb.com/docs/plugins/#generators

**Comment by aarongustafson** [comment]
2.6.0 includes the `source: false` option. Thanks for the pointer!
