### ISSUE TITLE
bundler: failed to load command: jekyll

### ISSUE THREAD

**Issue by calumryan** [aarongustafson/jekyll-webmention_io#42]
May be something in my own setup but trying to resolve this at the moment..

`remote: Bundler::GemRequireError: There was an error while trying to load the gem 'jekyll-webmention_io'.`
`remote: Gem Load Error is: uninitialized constant Jekyll::WebmentionIO::WebmentionTag`
`remote: Backtrace for gem load error is:`
`remote: /var/tmp/git/calumryan.com/vendor/bundle/ruby/2.4.0/gems/jekyll-webmention_io-2.1.0/lib/jekyll/tags/count.rb:12:in <module:WebmentionIO>`

**Comment by aarongustafson** [comment]
Hmm, I wonder if it is a directory sorting issue. The base `Class` loads in the tags:

```ruby
Dir[File.dirname(__FILE__) + '/tags/*.rb'].each do |file|
  require file
end
```

And the default one is `_.rb`, which _should_ sort first. But I can make it explicit and you can give that a try.

**Comment by aarongustafson** [comment]
@calumryan Can you try with a local version of the gem from the [`bugfixes-2017-07-17` branch](https://github.com/aarongustafson/jekyll-webmention_io/tree/bugfixes-2017-07-17)? I set it up to explicitly pull the `_.rb` file first before looping.

**Comment by aarongustafson** [comment]
Pushing the change now. Please re-open this bug if you still have issues with it.

**Comment by calumryan** [comment]
Tried with this however I seem to be having problems with running the bundler installation on my server deployment stage that's now preventing me from testing this further. This is probably related to other ruby gems and permissions possibly on my server. Persisting with that at the moment.
