### ISSUE TITLE
jekyll 3.4.3 | Error:  undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by nighcrawl** [aarongustafson/jekyll-webmention_io#47]
Hi,

Could you help me to fix this error, please ? Is there a problem with my Jekyll version or something ? 

```
Configuration file: /Users/angechierchia/Desktop/chierchia.fr/_config.yml
            Source: _source
       Destination: _deploy
 Incremental build: disabled. Enable with --incremental
      Generating... 
[jekyll-webmention_io] Beginning to gather webmentions of your posts. This may take a while. 
[jekyll-webmention_io] Webmentions have been gathered and cached. 
_source/js
[jekyll-webmention_io] Beginning to gather webmentions you’ve made. This may take a while. 
[jekyll-webmention_io] Webmentions have been gathered and cached. 
jekyll 3.4.3 | Error:  undefined method `[]' for nil:NilClass
```

**Comment by aarongustafson** [comment]
I'm on vacation this week and don't have anything with me except my phone. I can take a look next week.

**Comment by stuartbreckenridge** [comment]
Workaround for this is to use `js: false` in the webmention setup in the `_config.yml` file.

**Comment by aarongustafson** [comment]
@nighcrawl Can you run the script again with the `--trace` option on? That will help me suss out the source of the issue.

```bash
$> bundle exec jekyll build --trace
```

**Comment by aarongustafson** [comment]
I just pushed a potential fix (assuming this was a dupe of #46). Give 2.6.1 a shot and let me know if you have an issue.

**Comment by nighcrawl** [comment]
Thanks for your replies. I'll test it tonight

**Comment by aarongustafson** [comment]
@nighcrawl Awesome, thanks!

**Comment by nighcrawl** [comment]
I've done a `bundle update` to get the latest version before `bundle exec jekyll build` and it's all good.

Thanks for your time :)

**Comment by aarongustafson** [comment]
Awesome! Thanks for verifying!
