### ISSUE TITLE
jekyll webmention command cannot be found

### ISSUE THREAD

**Issue by stuartbreckenridge** [aarongustafson/jekyll-webmention_io#48]
After installing I have been able to get the plugin working as intended. However, the `jekyll webmention` command fails with the following error:

```
fatal: 'jekyll webmention' could not be found. You may need to install the jekyll-webmention gem or a related gem to be able to use this subcommand.
```

The error doesn't make much sense as the plugin working for other things.

**Comment by aarongustafson** [comment]
I'm on vacation this week and don't have anything with me except my phone. I can take a look next week.

**Comment by aarongustafson** [comment]
Hmm, did you try

```bash
$> bundle exec jekyll webmention
```

**Comment by stuartbreckenridge** [comment]
Yep.

**Comment by aarongustafson** [comment]
@stuartbreckenridge When you run `gem list` and `bundle list`, which versions of the gem do you see?

**Comment by stuartbreckenridge** [comment]
`gem list`:
`jekyll-webmention_io (2.6.1)`

`bundle list`:
`* jekyll-webmention_io (2.6.1)`

**Comment by aarongustafson** [comment]
Hmm, and you get the same fatal error in both scenarios?

**Comment by stuartbreckenridge** [comment]
Yep. I can't work it out.

`trace` doesn't reveal anything and the code seems to be in good shape. Will have another look this evening.

**Comment by aarongustafson** [comment]
Thanks! It’s perplexing for sure.

**Comment by stuartbreckenridge** [comment]
Still nothing on this. Does anyone else have the issue!? :-(

**Comment by nhoizey** [comment]
I don't have this issue, sorry.

**Comment by tomasparks** [comment]
yes I do
bundle list | gem list
jekyll-webmention_io (2.8.3)

**Comment by aarongustafson** [comment]
@tomasparks Can you post the results of `bundle exec jekyll`? It should look something like this:

```bash
Configuration file: /Users/aarongu/Dropbox/Sites/aaron-gustafson.com/_config.yml
A subcommand is required. 
jekyll 3.4.2 -- Jekyll is a blog-aware, static site generator in Ruby

Usage:

  jekyll <subcommand> [options]

Options:
        -s, --source [DIR]  Source directory (defaults to ./)
        -d, --destination [DIR]  Destination directory (defaults to ./_site)
            --safe         Safe mode (defaults to false)
        -p, --plugins PLUGINS_DIR1[,PLUGINS_DIR2[,...]]  Plugins directory (defaults to ./_plugins)
            --layouts DIR  Layouts directory (defaults to ./_layouts)
            --profile      Generate a Liquid rendering profile
        -h, --help         Show this message
        -v, --version      Print the name and version
        -t, --trace        Show the full backtrace when an error occurs

Subcommands:
  docs                  
  import                
  build, b              Build your site
  clean                 Clean the site (removes site output and metadata file) without building.
  doctor, hyde          Search site and print specific deprecation warnings
  help                  Show the help message, optionally for a given subcommand.
  new                   Creates a new Jekyll site scaffold in PATH
  new-theme             Creates a new Jekyll theme scaffold
  serve, server, s      Serve your site locally
  webmention            Sends queued webmentions
```

**Comment by tomasparks** [comment]
bundle exec jekyll
A subcommand is required. 
jekyll 3.6.0 -- Jekyll is a blog-aware, static site generator in Ruby

Usage:

  jekyll <subcommand> [options]

Options:
        -s, --source [DIR]  Source directory (defaults to ./)
        -d, --destination [DIR]  Destination directory (defaults to ./_site)
            --safe         Safe mode (defaults to false)
        -p, --plugins PLUGINS_DIR1[,PLUGINS_DIR2[,...]]  Plugins directory (defaults to ./_plugins)
            --layouts DIR  Layouts directory (defaults to ./_layouts)
            --profile      Generate a Liquid rendering profile
        -h, --help         Show this message
        -v, --version      Print the name and version
        -t, --trace        Show the full backtrace when an error occurs

Subcommands:
  docs                  
  import                
  build, b              Build your site
  clean                 Clean the site (removes site output and metadata file) without building.
  doctor, hyde          Search site and print specific deprecation warnings
  help                  Show the help message, optionally for a given subcommand.
  new                   Creates a new Jekyll site scaffold in PATH
  new-theme             Creates a new Jekyll theme scaffold
  serve, server, s      Serve your site locally

**Comment by tomasparks** [comment]
I've just setup a travis-ci acc for my website and I'm not getting a command not found for webmention :)

**Comment by tomasparks** [comment]
turns out I was mistaken :(

**Comment by aarongustafson** [comment]
What other plugins do you have? I wonder if another one is wreaking havoc on your commands.

**Comment by aarongustafson** [comment]
@stuartbreckenridge What's your `bundle exec jekyll` show you?

**Comment by tomasparks** [comment]
I've temporarily abandoned travis-ci

local setup to follow
gem list
addressable (2.5.2, 2.5.1, 2.4.0)
backports (3.8.0)
bibtex-ruby (4.4.4)
bigdecimal (default: 1.3.0)
bundler (1.16.0.pre.3, 1.15.4, 1.15.3)
citeproc (1.0.5)
citeproc-ruby (1.1.7)
colorator (1.1.0)
concurrent-ruby (1.0.5)
csl (1.4.5)
csl-styles (1.0.1.8)
did_you_mean (1.1.0)
domain_name (0.5.20170404)
ethon (0.10.1)
execjs (2.7.0)
exifr (1.3.1)
extras (0.3.0)
faraday (0.13.1)
faraday_middleware (0.12.2)
fastimage (2.1.0)
ffi (1.9.18)
forwardable-extended (2.6.0)
gh (0.15.1)
highline (1.7.8)
htmlbeautifier (1.3.1)
http (2.2.2)
http-cookie (1.0.3)
http-form_data (1.0.3)
http_parser.rb (0.6.0)
httparty (0.15.6)
io-console (default: 0.4.6)
jekyll (3.6.0, 3.5.2, 3.3.1)
jekyll-archives (2.1.1)
jekyll-asciinema (0.2.0)
jekyll-assets (2.4.0, 2.3.2)
jekyll-feed (0.9.2)
jekyll-last-modified-at (1.0.1)
jekyll-lunr-js-search (3.3.0)
jekyll-paginate (1.1.0)
jekyll-paginate-v2 (1.9.0, 1.8.1)
jekyll-pandoc (2.0.1)
jekyll-pandoc-multiple-formats (0.2.9.1)
jekyll-redirect-from (0.12.1)
jekyll-responsive_image (1.0.1)
jekyll-sass-converter (1.5.0)
jekyll-scholar (5.10.2)
jekyll-seo-tag (2.3.0, 2.2.3)
jekyll-watch (1.5.0)
jekyll-webmention_io (2.8.4, 2.8.3)
json (2.1.0, default: 2.0.2)
kramdown (1.15.0, 1.14.0)
latex-decode (0.2.2)
launchy (2.4.3)
libv8 (3.16.14.19 x86_64-linux)
link_header (0.0.8)
liquid (4.0.0, 3.0.6)
listen (3.0.8)
mercenary (0.3.6)
mini_portile2 (2.3.0, 2.2.0)
minima (2.1.1)
minitest (5.10.1)
multi_json (1.12.2)
multi_xml (0.6.0)
multipart-post (2.0.0)
namae (0.11.3)
net-http-persistent (2.9.4)
net-http-pipeline (1.0.1)
net-telnet (0.1.1)
nokogiri (1.8.1, 1.8.0)
openssl (2.0.6, default: 2.0.3)
pandoc-ruby (2.0.2, 2.0.1)
pathutil (0.16.0, 0.14.0)
pdf_info (0.5.3)
posix-spawn (0.3.13)
power_assert (0.4.1)
psych (default: 2.2.2)
public_suffix (3.0.0, 2.0.5)
pusher-client (0.6.2)
rack (1.6.8)
rake (12.1.0, 12.0.0, 10.1.1)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
rdoc (default: 5.0.0)
ref (2.0.0)
rmagick (2.16.0)
rouge (2.2.1, 1.11.1)
rtex (2.1.1)
safe_yaml (1.0.4)
sass (3.5.2, 3.5.1)
sass-listen (4.0.0)
sprockets (3.7.1)
string_inflection (0.1.2)
test-unit (3.2.3)
therubyracer (0.12.3)
travis (1.8.8)
typhoeus (0.8.0)
uglifier (3.2.0)
unf (0.1.4)
unf_ext (0.0.7.4)
unicode (0.4.4.4)
webmention (0.1.6)
websocket (1.2.4)
xmlrpc (0.2.1)
bundle list
  * addressable (2.5.2)
  * bibtex-ruby (4.4.4)
  * bundler (1.16.0.pre.3)
  * citeproc (1.0.5)
  * citeproc-ruby (1.1.7)
  * colorator (1.1.0)
  * concurrent-ruby (1.0.5)
  * csl (1.4.5)
  * csl-styles (1.0.1.8)
  * domain_name (0.5.20170404)
  * execjs (2.7.0)
  * extras (0.3.0)
  * fastimage (2.1.0)
  * ffi (1.9.18)
  * forwardable-extended (2.6.0)
  * htmlbeautifier (1.3.1)
  * http (2.2.2)
  * http-cookie (1.0.3)
  * http-form_data (1.0.3)
  * http_parser.rb (0.6.0)
  * httparty (0.15.6)
  * jekyll (3.6.0)
  * jekyll-asciinema (0.2.0)
  * jekyll-assets (2.4.0)
  * jekyll-last-modified-at (1.0.1)
  * jekyll-lunr-js-search (3.3.0)
  * jekyll-paginate-v2 (1.9.0)
  * jekyll-pandoc (2.0.1)
  * jekyll-redirect-from (0.12.1)
  * jekyll-responsive_image (1.0.1)
  * jekyll-sass-converter (1.5.0)
  * jekyll-scholar (5.10.2)
  * jekyll-seo-tag (2.3.0)
  * jekyll-watch (1.5.0)
  * jekyll-webmention_io (2.8.4)
  * json (2.1.0)
  * kramdown (1.15.0)
  * latex-decode (0.2.2)
  * libv8 (3.16.14.19)
  * link_header (0.0.8)
  * liquid (4.0.0)
  * listen (3.0.8)
  * mercenary (0.3.6)
  * mini_portile2 (2.3.0)
  * multi_xml (0.6.0)
  * namae (0.11.3)
  * nokogiri (1.8.1)
  * openssl (2.0.6)
  * pandoc-ruby (2.0.2)
  * pathutil (0.16.0)
  * posix-spawn (0.3.13)
  * public_suffix (3.0.0)
  * rack (1.6.8)
  * rake (12.1.0)
  * rb-fsevent (0.10.2)
  * rb-inotify (0.9.10)
  * ref (2.0.0)
  * rmagick (2.16.0)
  * rouge (2.2.1)
  * safe_yaml (1.0.4)
  * sass (3.5.2)
  * sass-listen (4.0.0)
  * sprockets (3.7.1)
  * string_inflection (0.1.2)
  * therubyracer (0.12.3)
  * uglifier (3.2.0)
  * unf (0.1.4)
  * unf_ext (0.0.7.4)
  * unicode (0.4.4.4)
  * webmention (0.1.6)

**Comment by aarongustafson** [comment]
@tomasparks Is your project in a public repo? Alternately, can you paste the `gems` key contents from your `_config.yml`?

**Comment by tomasparks** [comment]
@aarongustafson yes https://github.com/tomasparks/website

**Comment by aarongustafson** [comment]
Found your issue @tomasparks (and maybe yours @stuartbreckenridge): You didn’t place the gem in the `:jekyll_plugins` group

```ruby
group :jekyll_plugins do
  gem 'jekyll-webmention_io'
end
```
