### ISSUE TITLE
"Liquid Exception: Socket is not connected"

### ISSUE THREAD

**Issue by borisschapira** [aarongustafson/jekyll-webmention_io#5]
First, let me thank you for this plugin. Then, I wanted to point out an exception in case somebody has determined how to stop it (maybe @calumryan) ?

Everytime I launch my serve script and modify one file, the exception is thrown :

```bash
      Regenerating: 1 file(s) changed at 2016-02-18 14:37:35   Liquid Exception: Socket is not connected in _includes/post-mentions.html, included in _layouts/post.html
...error:
             Error: Socket is not connected
             Error: Run jekyll build --trace for more information.
      Regenerating: 2 file(s) changed at 2016-02-18 14:37:54   Liquid Exception: Socket is not connected in _includes/post-mentions.html, included in _layouts/post.html
...error:
             Error: Socket is not connected
             Error: Run jekyll build --trace for more information.
      Regenerating: 1 file(s) changed at 2016-02-18 14:37:55   Liquid Exception: Socket is not connected in _includes/post-mentions.html, included in _layouts/post.html
```

`post-mentions.html` is the _include_ where the webmention tag is used.

My setup is here : https://github.com/borisschapira/jekyll/blob/master/Gemfile.lock, revolving around Jekyll 3.1.1.

**Comment by aarongustafson** [comment]
Do you have `encoding: utf-8` in your _config? Just checking against other known Jekyll bugs first :-)

**Comment by borisschapira** [comment]
I don't manage to reproduce the bug anymore, I'm sorry. I updated a few gems and changed a lot of layout. If I reproduce it, I'll reopen. Sorry for the noise.
