### ISSUE TITLE
Standardize naming of liquid tags

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#55]
There is currently a mix between singular and plural forms of "webmention":
- webmention**S**
- webmention_count
- webmention_likes
- …

Maybe it would be easier for users if the same form is always used.

I had a problem, because I used a plural for webmention**s**_count, and lost time finding why it didn't give me anything.

The singular form is in the plugin name, but the former version of the plugin (without a gem) already had the webmention**s** tag…

**Comment by aarongustafson** [comment]
I understand where you’re coming from, but I’d argue it is consistent overall. The only real questionable one (to my mind) is the `webmention_count` tag. I’m happy to alias that tag to `webmentions_count` if you like. In all of the other instances, the tag is plural ("likes", etc.)

**Comment by aarongustafson** [comment]
Does that work for you, @nhoizey?

**Comment by nhoizey** [comment]
Yes, it is better like this, thanks!
