### ISSUE TITLE
Collect Twitter Webmentions not in Brid.gy

### ISSUE THREAD

**Issue by aarongustafson** [aarongustafson/jekyll-webmention_io#56]
I have a rake task that gathers any mentions of a URL and supplements brid.gy data. I could add it as a command if there’s interest. It would require a Twitter API key.

Thoughts? @nhoizey @alias1 @stuartbreckenridge @eminaksehirli

**Comment by alias1** [comment]
That sounds cool. Didn't realise bridgy didn't do that already

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aarongustafson** [comment]
I've seen a few missing ones. Some predate Brid.gy.

**Comment by nhoizey** [comment]
It would be nice, indeed!

**Comment by twhite96** [comment]
I'd love this as well. I am using your plugin as it is the most comprehensive one I've found but Bridgy support would be great.

**Comment by aarongustafson** [comment]
@twhite96 Brid.gy support is already in there (webmention.io uses brid.gy), but I will look into rolling this in and putting it behind a feature flag since it is considerably more expensive as an operation.

**Comment by twhite96** [comment]
@aarongustafson okay. Weird. I have some Bridgy mentions that aren't showing up on my site. I'll have to dig further as to why that is.

**Comment by aarongustafson** [comment]
@twhite96 Interesting. I wonder if it’s an issue of webmention.io not being fully synced? @aaronpk any ideas?

**Comment by twhite96** [comment]
@aarongustafson There is a warning about webmentions not being supported when I look at webmentions on Bridgy for my site. I have everything setup but I am thinking I configured something wrong. I'll have to test it with webmention.rocks.

**Comment by aaronpk** [comment]
You might be able to find the webmention.io status URL for the webmentions listed in the bridgy debug logs in order to see whether webmention.io was able to process them successfully.

**Comment by aarongustafson** [comment]
Thank you @aaronpk!

**Comment by aarongustafson** [comment]
I kept having Ruby/Jekyll issues when upgrading my Mac, so I have moved off of Jekyll and will not be working on this project anymore, going forward. I am going to flag this as won’t fix, but leave it open in case someone else wants to pick up the project from here.

**Comment by twhite96** [comment]
@aarongustafson Let me know how you're liking 11ty!

**Comment by fancypantalons** [comment]
Closing this for now as a) I don't have Aaron's proposed code, b) there's not been much activity on this ticket for a while so it's not showing a lot of interest, and c) Twitter's API might get neutered, soon, which may limit the utility in any case.

Can always revisit and reopen if there's renewed interest.
