### ISSUE TITLE
Make webmentions_count a "real" number

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#57]
I've lost some time wondering why this liquid test didn't give me the result I was waiting for:

```Liquid
{{ webmentions_count }} webmention{% if webmentions_count > 1 %}s{% endif %}
```

It looks like `webmentions_count` is an HTML fragment, instead of just the number I was expecting.

The README says "The output will be a number".

IMHO, the HTML should be in the templates, and `webmentions_count` should indeed be a number.

**Comment by aarongustafson** [comment]
You can replace the default `count` template to make it a raw number if you like. Since it can be filtered I added the additional markup details.

**Comment by nhoizey** [comment]
You're right! I didn't see it was also a template.
