### ISSUE TITLE
Jekyll 3.1 error:  Liquid Exception: undefined method `getConverterImpl'

### ISSUE THREAD

**Issue by lewisnyman** [aarongustafson/jekyll-webmention_io#6]
I fixed this easily here: https://github.com/lewisnyman/lewisnyman.co.uk-source/commit/5cef5e6f12700b6cca3d51f402632dde924f0db7

Do we need a branch for each breaking version of Jekyll or Ruby? I don't know

**Comment by aarongustafson** [comment]
We can do it conditionally in the code. Whatever happened to aliasing?

**Comment by aarongustafson** [comment]
Fixed with 5344e44
