### ISSUE TITLE
Unable to use my own "likes" template

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#60]
I've been trying to use my own template for the likes, so that I can use Cloudinary to optimize avatars:

https://github.com/nhoizey/nicolas-hoizey.com/blob/master/_includes/webmentions/likes.html

I've made the necessary settings, I think:

https://github.com/nhoizey/nicolas-hoizey.com/blob/master/_config.yml#L80-L81

But it keeps using the default template :

https://nicolas-hoizey.com/2017/07/so-long-disqus-hello-webmentions.html#webmentions_likes

Did I forgot something?

**Comment by aarongustafson** [comment]
Can you uncomment `Jekyll::WebmentionIO::log 'info', "Template file: #{template_file}"` inside `get_template_contents` and let me know what it says for that template?

**Comment by nhoizey** [comment]
I can't find where bundler put the gem, because I use the github URL in my Gemfile to have the latest master version, instead of the packaged version.

Do you have any idea where it is, on macOS?

**Comment by nhoizey** [comment]
Well, found it!

I was using `gem which jekyll-webmention_io` when I should have used `bundle show jekyll-webmention_io`…

**Comment by nhoizey** [comment]
So, it uses the default template:

```
[jekyll-webmention_io] Template file: /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-b4ddd816f3a9/lib/jekyll/templates/likes.html
```

**Comment by nhoizey** [comment]
Well, I just noticed my other settings weren't used either, so the issue should be on my side, obviously.

And it was, sorry for the lost time hunting:
https://github.com/nhoizey/nicolas-hoizey.com/commit/478fe646342396699e550b8236b2f117d9b2ecec
