### ISSUE TITLE
Rework webmention rakefile as a command/hook?

### ISSUE THREAD

**Issue by alias1** [aarongustafson/jekyll-webmention_io#7]
It would be cool to have the webmention rakefile reworked in a way that feels more 'Jekyll 3'
- https://jekyllrb.com/docs/plugins/#commands
- https://jekyllrb.com/docs/plugins/#hooks

Would you be up for having something like this?

**Comment by aarongustafson** [comment]
I am (personally) waiting on Octopress to upgrade :-)

**Comment by aarongustafson** [comment]
I added a command for sending webmentions to the forthcoming gem.
