### ISSUE TITLE
Add support for RSVP

### ISSUE THREAD

**Issue by aarongustafson** [aarongustafson/jekyll-webmention_io#76]
Reviving this from a [dead PR](https://github.com/aarongustafson/jekyll-webmention_io/pull/71/).

**Comment by aarongustafson** [comment]
FYI @calumryan

**Comment by calumryan** [comment]
Thanks @aarongustafson will give it a go for some IndieWeb events I'm organising

**Comment by aarongustafson** [comment]
Awesome! Docs should be up to date.

I also added support for collections in this release in case you are using
those over posts.
