### ISSUE TITLE
Move docs from README to the Wiki?

### ISSUE THREAD

**Issue by aarongustafson** [aarongustafson/jekyll-webmention_io#77]
Thoughts?

+@nhoizey @stuartbreckenridge @DirtyF

**Comment by DirtyF** [comment]
When README becomes too bloated, we tend to split it in several pages and use the `docs` folder +          [primer theme](https://github.com/pages-themes/primer) rather than the wiki. It allows you to keep the same workflow and have an URL for the documentation.

**Comment by aarongustafson** [comment]
@DirtyF Smart

**Comment by aarongustafson** [comment]
Ok, I made the move over to `/docs/`. Should make things easier to maintain from here on out.

Fixed as of d6df6da.

**Comment by clawfire** [comment]
Doc isn't published in the github pages so all the links are broken
