### ISSUE TITLE
Don't collect outgoing mentions from localhost

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#82]
When run locally, jekyll-webmention_io currently collects outgoing mention when running `jekyll serve`.

<img width="620" alt="image" src="https://user-images.githubusercontent.com/78213/40357596-05c2abe6-5dbd-11e8-83d9-fcdaed87364f.png">

**Comment by aarongustafson** [comment]
@nhoizey Fixed in v2.9.3
